### ISSUE TITLE
css : duplicated files

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#11]
You have 2 CSS files with same content (`styles/styles.css` and `styles.css` which is the minified form)

1. CSS should be store in styles.css or in style/whateveryouwant.css (https://docs.moodle.org/dev/CSS_Coding_Style#File_naming
2. CSS should NOT be minified (https://docs.moodle.org/dev/CSS_Coding_Style#Properties_and_values)

So you should :  
* remove `styles/styles.css` and unminify `styles.css`
* or rename `styles/styles.css` to `style/styles.css` and remove `styles.css`

**Comment by ranjitlawale11** [comment]
We have kept unminified CSS in styles/remuiformatstyles.css and required minified CSS file styles.css to improve performance.

Renamed styles/styles.css to styles/remuiformatstyles.css.

**Comment by ak4t0sh** [comment]
https://docs.moodle.org/dev/CSS_Coding_Style#Properties_and_values
Style should not be minified. Moodle will take care of it.

**Comment by ranjitlawale11** [comment]
We have removed the minified CSS file from the plugin.
