### ISSUE TITLE
hardcoded strings

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#13]
`section_renderable.php` has hardcoded strings : 
https://github.com/WisdmLabs/moodle-format_remuiformat/blob/21c079729ac75dd136124a7441763b42615372ed/classes/output/section_renderable.php#L236
https://github.com/WisdmLabs/moodle-format_remuiformat/blob/21c079729ac75dd136124a7441763b42615372ed/classes/output/section_renderable.php#L240

**Comment by ranjitlawale11** [comment]
Removed hardcoded string from the PHP file.

Add sting into the language file.
