### ISSUE TITLE
string api usage

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#15]
in `abstract_html_contents()` in lib.php you are using mb_* functions.
You should use Moodle string API `core_text` class when possible.

**Comment by ranjitlawale11** [comment]
Use Moodle core_text class functions instead of mb_* functions.

**Comment by ak4t0sh** [comment]
Not fixed. You do not implements String API (https://docs.moodle.org/dev/String_API)
You removed `mb_` prefix and use "standard" php `strlen` and `substr` functions
You should use `core_text::strlen()` and `core_text::substr`

**Comment by ak4t0sh** [comment]
This issue is not fixed. You removed `mb_` and now are using `strlen` and `substr` which do not handle utf8 correctly.
You should use `core_text` class from Moodle API (link to doc in my last comment)
