### ISSUE TITLE
switch list to card does not correctly update course layout field

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#17]
Switching from list to card mode do not correctly update "Course layout" field

**Steps to reproduce:**
* Create course with "List layout" and Course layout "Show all sections on one page"
* Edit course settings and switch to "Card layout"

**Actual**
![image](https://user-images.githubusercontent.com/2222386/60352722-c179ba80-99c8-11e9-9d5e-205cfde46f6b.png)

**Expected**
Select "Show one section per page

Note : this is not a blocker for approval

**Comment by ranjitlawale11** [comment]
This issue has been resolved.
