### ISSUE TITLE
Drag&Drop Upload Problem

### ISSUE THREAD

**Issue by kobajashi77** [WisdmLabs/moodle-format_remuiformat#23]
Files uploaded via d&d are not placed in the collapsible section. 

<img width="1337" alt="Bildschirmfoto 2019-08-27 um 19 25 52" src="https://user-images.githubusercontent.com/4180517/63796334-2b99d780-c906-11e9-979f-ce829d56bde1.png">

**Comment by ranjitlawale11** [comment]
We have fixed this issue and will make this live in the next update.
