### ISSUE TITLE
Use grunt to minify AMD code

### ISSUE THREAD

**Issue by ewallah** [WisdmLabs/moodle-format_remuiformat#28]
Moodle needs 2 versions of the AMD code: a minified version and a normal version for debugging purposes.  Using grunt, these versions should be automatically created.

If you do not provide both versions, [PHPUnit](https://docs.moodle.org/dev/PHPUnit) complains:
```
core_requirejs_testcase::test_requirejs
Failed asserting that 'course/format/remuiformat/amd/build/jquery.dragsort.js' contains ".min".

lib/tests/requirejs_test.php:91
lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "core_requirejs_testcase" lib/tests/requirejs_test.php
```

**Comment by ranjitlawale11** [comment]
This is fixed and will be released in next update.
