### ISSUE TITLE
Error in Card layout

### ISSUE THREAD

**Issue by naamaan** [WisdmLabs/moodle-format_remuiformat#34]
Hi,
I'm using Moodle 3.8 and trying your course format, in Card layout I got this error message:

> Notice: Undefined variable: output in /var/www/html/moodle/course/format/remuiformat/classes/output/card_all_sections_summary_renderable.php on line 175
>
> Notice: Trying to access array offset on value of type null in /var/www/html/moodle/course/format/remuiformat/classes/output/card_all_sections_summary_renderable.php on line 175

Any help is appreciated.

![error-snap](https://user-images.githubusercontent.com/2176593/85223773-11b60d80-b3ce-11ea-9a66-fb67c293c47c.png)

Best regards,

**Comment by wisdmyogeshshirsath** [comment]
It is fixed.
