### ISSUE TITLE
Issue with Oracle

### ISSUE THREAD

**Issue by kdima71** [WisdmLabs/moodle-format_remuiformat#61]
Hi Edwiser Team!

I am getting this error above my course:

Exception encountered in event observer '\format_remuiformat\observers\course_module::viewed':

ORA-01747: invalid user.table.column, table.column, or column specification INSERT INTO m_remuiformat_course_visits (course,user,cm,timevisited) VALUES (:course,:user,:cm,:timevisited)
-- line 1328 of \lib\dml\oci_native_moodle_database.php: call to oci_native_moodle_database->insert_record_raw()
-- line 68 of \course\format\remuiformat\classes\observers\course_module.php:
call to oci_native_moodle_database->insert_record() -- line unknown of unknownfile:
call to format_remuiformat\observers\course_module::viewed()
-- line 155 of \lib\classes\event\manager.php: call to call_user_func()
-- line 75 of \lib\classes\event\manager.php: call to core\event\manager::process_buffers()
-- line 834 of \lib\classes\event\base.php: call to core\event\manager::dispatch()
-- line 516 of \mod\page\lib.php: call to core\event\base->trigger()
-- line 55 of \mod\page\view.php: call to page_view() RETURNING id INTO :oracle_id [array ( 'course' => '242', 'user' => '2', 'cm' => '566', 'timevisited' => 1661022762, )])

The thing is, I'm using Oracle.
The table «m_remuiformat_course_visits» uses Oracle's predefined «user» name as a field.

I'm waiting for this bug to be fixed.

Thanks in advance.

**Comment by wisdmyogeshshirsath** [comment]
Fixed
