### ISSUE TITLE
superglobals access

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#7]
In [lib.php#491](https://github.com/WisdmLabs/moodle-format_remuiformat/blob/21c079729ac75dd136124a7441763b42615372ed/lib.php#L491) 
`$_POST` and `$_GET` direct access shoud be replaced by `optional_param()`

**Comment by ranjitlawale11** [comment]
Fixed issue, superglobals access.

Used optional_param() to get the course format.
