### ISSUE TITLE
missing boilerplates

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#8]
mustache and javascript files do not have correct boilerplate
  
Exemple :
For javascript : [theme/boost/amd/src/aria.js](https://github.com/moodle/moodle/blob/master/theme/boost/amd/src/aria.js)
For mustache : [theme/boost/templates/admin_setting_tabs.mustache](https://github.com/moodle/moodle/blob/master/theme/boost/templates/admin_setting_tabs.mustache)

**Comment by ranjitlawale11** [comment]
Added correct boilerplate in mustache and JS files.
