### ISSUE TITLE
Repository's tag v4.1.4 points to wrong commit

### ISSUE THREAD

**Issue by phager-at** [WisdmLabs/moodle-format_remuiformat#86]
It seems the repository's git tag v4.1.4 erroneously points to the 2 year old version v1.1.1 (+1 commit deleting package-lock.json) at commit hash 199ad958d4f8c6c63dca4a4e81e523751a017d7c instead of v4.1.4's commit hash 96c6527f593b893ec40ed4376277783f68738f18.

**Comment by abhikushwah** [comment]
Issue resolved
