### ISSUE TITLE
Licensing : missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by ak4t0sh** [WisdmLabs/moodle-format_remuiformat#9]
https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing

When you use Third party libs you have to define them in [Plugin_files#thirdpartylibs.xml](https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml)

At first sight you use at least 2 external lib in your JS (jQuery UI Touch Punch and jQuery List DragSort)

**Comment by ranjitlawale11** [comment]
Added thirdpartylibs.xml file.

Added details of the external lib (jQuery UI Touch Punch and jQuery List DragSort)
